---
language: node_js
node_js:
  - "10"

sudo: false
dist: xenial

addons:
  chrome: stable

cache:
  directories:
    - node_modules
    - $HOME/.npm
    - $HOME/.cache

before_install:
  - npm config set spin false
  - npm install -g bower
  - bower --version

install:
  - npm install
  - bower install

branches:
  only:
    - master

script:
  - npm test
